export { default as Buzzdgame } from "./buzzdgame.jpg";
export { default as ShBilpleie } from "./shbilpleie.jpg";
export { default as SocialCampus } from "./socialcampus.jpg";
export { default as Mattilsynet } from "./mattilsynet.jpg";
export { default as Tegneprogram } from "./tegneprogram.jpg";
export { default as SocialCampusApp } from "./socialcampus-app.jpg";
export { default as QuizApp } from "./quizapp.jpg";
export { default as Kobo } from "./kobo.jpg";
export { default as Statnett } from "./statnett.png";
